import { escape as e, icon, iconButton, categoryIcon, color, amount, recordRow, tableRows, empty, errorPanel, dayLabel } from './ui.js';
import { money, PALETTE, DEFAULT_CATEGORIES } from '../shared/format.js';

const colorNames = { blue: '蓝色', orange: '橙色', green: '绿色', purple: '紫色', slate: '灰色', brown: '棕色', pink: '粉色', red: '红色', teal: '青色', indigo: '靛蓝', olive: '橄榄绿', amber: '琥珀色' };
export const NAV = [['record', 'pencil', '记一笔'], ['bills', 'receipt', '账单'], ['stats', 'stats', '统计'], ['settings', 'user', '我的']];
const titles = { record: '记一笔', bills: '账单', stats: '收支概览', settings: '我的账本' };
export function monthControl(state) {
  return `<div class="month-control">${iconButton('left', '上一期间', 'data-action="previous-month"')}<label class="month-picker"><span>${e(state.month.replace('-', '年'))}月</span>${icon('down', 15)}<input type="month" aria-label="选择月份" value="${e(state.month)}" min="1900-01" max="2100-12" data-action="month" /></label>${iconButton('right', '下一期间', 'data-action="next-month"')}</div>`;
}
export function mobileTools(state) {
  if (!state.session) return '';
  if (state.page === 'bills') return `<div class="mobile-tools" aria-label="账单操作">${monthControl(state)}<button class="button secondary" data-action="filters">${icon('filter',18)}筛选</button></div>`;
  if (state.page === 'stats') return `<div class="mobile-tools" aria-label="统计操作">${monthControl(state)}<button class="button secondary" data-action="stats-options">${icon(state.chart,18)}视图</button></div>`;
  if (state.page === 'settings') return `<div class="mobile-tools settings-tools" aria-label="数据操作"><button class="button secondary" data-action="export-all">${icon('download',18)}导出账单</button><button class="button primary" data-action="backup">${icon('upload',18)}备份与恢复</button></div>`;
  if (state.page === 'record') return `<div class="mobile-tools record-tools" aria-label="记账操作"><button class="button secondary" data-action="text-records">${icon('file',18)}文字记账${state.textSummary?.reminder_count?'<i class="reminder-dot"></i>':''}</button><button class="button primary" type="submit" form="entry-form-main" ${state.draft?.saving?'disabled':''}>${state.draft?.saving?'保存中…':state.draft?.pending?'核对并重试':'保存记录'}</button></div>`;
  return '';
}
export function shell(state, body) {
  const ledger = state.session?.ledger;
  const links = place => NAV.map(([id, symbol, label]) => `<a href="/${id}" data-route="${id}" aria-label="${label}" class="nav-item ${state.page === id ? 'active' : ''}" ${state.page === id ? 'aria-current="page"' : ''}>${icon(symbol, place === 'mobile' ? 24 : 21)}<span>${label}</span></a>`).join('');
  return `<aside class="sidebar"><a class="brand" href="/stats" data-route="stats"><span class="brand-mark">M</span>MoneyTalk<span class="brand-dot"></span></a><button class="ledger-switch" data-action="ledgers">${e(ledger?.name || '个人账本')}${icon('down', 14)}</button><nav aria-label="主要导航">${links('desktop')}</nav><div class="sidebar-bottom"><button data-action="backup" aria-label="设置与导出">${icon('settings')}<span>设置与导出</span>${icon('right', 15)}</button><div class="sidebar-note">清晰记录每一笔<div>${state.session?.local ? '本地预览 · 数据保存在此 Mac' : '你的私人账本'}</div></div></div></aside><div class="app-workspace"><header class="page-header"><div><h1 class="desktop-title">${titles[state.page]}</h1><h1 class="mobile-title">${NAV.find(x => x[0] === state.page)?.[2] || 'MoneyTalk'}</h1><p class="page-subtitle">${state.page === 'stats' ? '清晰记录每一笔，掌握更好的生活' : state.page === 'bills' ? '每一笔收支，都有迹可循' : state.page === 'record' ? '记录当下，让生活更有数' : '管理你的账本与数据'}</p></div><div class="header-actions">${['stats', 'bills'].includes(state.page) ? monthControl(state) : `<span class="private-label">${icon('shield', 16)}${state.session?.local ? '本地预览' : '私人账本'}</span>`}<button class="button primary" data-action="new-entry">${icon('plus', 18)}记一笔</button></div></header><main id="main" tabindex="-1" class="page-content page-${state.page}">${state.error ? errorPanel(state.error) : body}</main><div class="mobile-environment">${state.session?.local ? '本地预览 · 数据保存在此 Mac' : ''}</div></div>${mobileTools(state)}<nav class="mobile-nav" aria-label="手机导航">${links('mobile')}</nav>`;
}
export function summary(totals, prefix = '本月', small = false) {
  const data = [['wallet', 'expense', '支出', totals.expense_minor], ['income', 'income', '收入', totals.income_minor], ['pie', 'balance', '结余', totals.income_minor - totals.expense_minor]];
  return `<div class="summary-cards ${small ? 'small-summary' : ''}">${data.map(([symbol, type, label, value]) => `<div class="summary-card ${type}"><span class="summary-icon">${icon(symbol, 27)}</span><div><span class="summary-label">${prefix}${label}</span><strong class="summary-value money ${money(value).length > 17 ? 'extra-long-money' : money(value).length > 12 ? 'long-money' : ''}">${money(value)}</strong></div>${type === 'balance' ? '<span class="sr-only">本期收入减支出，不代表账户余额</span>' : ''}</div>`).join('')}</div>`;
}
export function entryForm(draft, state, context = 'main') {
  const cats = state.categories.filter(c => c.type === draft.type && (!c.archived || c.id === draft.category_id));
  let visible = draft.expanded ? cats : cats.slice(0, 4);
  const selected = cats.find(c => c.id === draft.category_id);
  if (selected && !visible.includes(selected)) visible = [...visible.slice(0, 3), selected];
  const busy = Boolean(draft.saving), locked = busy || Boolean(draft.pending);
  return `<form id="entry-form-${context}" class="record-form ${context === 'quick' ? 'quick-form' : ''}" data-form="entry" data-context="${context}" novalidate>
    ${context === 'quick' ? '<h2>快速记一笔</h2>' : ''}
    <fieldset ${locked ? 'disabled' : ''}>
      <div class="form-top"><div class="segmented type-switch"><button type="button" aria-pressed="${draft.type === 'expense'}" class="${draft.type === 'expense' ? 'active' : ''}" data-action="entry-type" data-value="expense" data-context="${context}">支出</button><button type="button" aria-pressed="${draft.type === 'income'}" class="${draft.type === 'income' ? 'active' : ''}" data-action="entry-type" data-value="income" data-context="${context}">收入</button></div>${context === 'quick' ? '' : `<label class="date-control">${icon('calendar', 17)}<span>${Number(draft.occurred_on.slice(5, 7))}月${Number(draft.occurred_on.slice(8))}日</span>${icon('down', 14)}<input name="occurred_on" type="date" aria-label="记账日期" required value="${e(draft.occurred_on)}" min="1900-01-01" max="${state.session?.today || '2100-12-31'}" /></label>`}</div>
      <label class="amount-label" for="amount-${context}">金额</label><div class="amount-input"><span>¥</span><input id="amount-${context}" name="amount" class="${draft.amount.length > 10 ? 'long-value' : ''}" type="text" inputmode="decimal" autocomplete="off" aria-describedby="entry-error-${context}" value="${e(draft.amount)}" placeholder="0.00" maxlength="24" /></div>
      <span class="field-label">分类</span><div class="category-chips ${draft.expanded ? 'expanded' : ''}" role="group" aria-label="${draft.type === 'expense' ? '支出' : '收入'}分类">${visible.map(c => `<button type="button" title="${e(c.name)}" aria-label="${e(c.name)}" class="chip ${c.id === draft.category_id ? 'active' : ''}" data-action="entry-category" data-id="${e(c.id)}" data-context="${context}" aria-pressed="${c.id === draft.category_id}"><span style="--category:${color(c)}">${icon(c.icon, 16)}<span>${e(c.name)}</span></span></button>`).join('')}${cats.length > 4 ? `<button type="button" class="chip-expand" data-action="expand-categories" data-context="${context}" aria-expanded="${Boolean(draft.expanded)}" aria-label="${draft.expanded ? '收起分类' : '展开全部分类'}">${icon(draft.expanded ? 'up' : 'down', 17)}</button>` : ''}</div>
      ${!cats.length ? '<p class="field-error">暂无可用分类，请先到“我的”添加分类。</p>' : ''}
      ${context === 'quick' ? `<span class="field-label">日期</span><label class="date-control">${icon('calendar', 17)}<span>${Number(draft.occurred_on.slice(5, 7))}月${Number(draft.occurred_on.slice(8))}日</span>${icon('down', 14)}<input name="occurred_on" type="date" aria-label="记账日期" required value="${e(draft.occurred_on)}" min="1900-01-01" max="${state.session?.today || '2100-12-31'}" /></label>` : ''}
      <label class="field-label note-label" for="note-${context}">备注 <span>（选填）</span></label><div class="note-input"><textarea id="note-${context}" name="note" rows="2" maxlength="200" placeholder="这笔钱用在了哪里？">${e(draft.note)}</textarea><span class="char-count">${draft.note.length}/200</span></div>
    </fieldset>
    <div class="field-error" id="entry-error-${context}" role="alert">${e(draft.error || '')}${draft.conflict ? `<button type="button" class="text-button" data-action="reload-entry" data-id="${e(draft.id)}">放弃当前修改，载入最新记录</button>` : ''}</div>
    <button class="button primary save-button" type="submit" ${busy ? 'disabled' : ''}>${busy ? icon('loader', 18) : ''}${busy ? '正在保存…' : draft.pending ? '核对并重试' : draft.id ? '保存修改' : '保存记录'}</button>
    ${!draft.id && (draft.amount || draft.note) ? '<p class="draft-label">未保存草稿 · 仅保留在当前浏览器会话</p>' : ''}
  </form>`;
}
export function recent(state, isTable = false) {
  const entries = state.recent?.entries || [];
  return `<section class="card recent-card"><div class="card-heading"><h2>${isTable ? '最近账单' : '最近记录'}${isTable ? '<small>仅显示最近记录，非完整账单</small>' : ''}</h2><a class="text-button" href="/bills" data-route="bills">查看全部 ${icon('right', 15)}</a></div>${entries.length ? isTable ? `<div class="table-scroll"><table class="entries-table"><thead><tr><th>日期</th><th>备注</th><th>分类</th><th class="numeric">金额</th><th>操作</th></tr></thead><tbody>${tableRows(entries.slice(0, 6))}</tbody></table></div>` : entries.slice(0, 2).map(x => recordRow(x, { date: true })).join('') : empty('从第一笔开始', '记下今天的一笔收支，它就会出现在这里。')}</section>`;
}
export function recordPage(state) { return `${state.receipt?`<section class="save-receipt" role="status"><span class="receipt-symbol">${icon('checks',23)}</span><div><strong>已入账 · ${state.session?.local?'本地已保存':'云端已保存'}</strong><p>${e(state.receipt.from)}${state.receipt.to!==state.receipt.from?` 至 ${e(state.receipt.to)}`:''} · ${state.receipt.count} 笔</p></div><button class="text-button" data-action="view-receipt">查看账单 ${icon('right',16)}</button></section>`:''}<div class="record-layout"><section class="card entry-card"><button class="button secondary text-open" data-action="text-records">文字记账${state.textSummary?.reminder_count ? ` · ${state.textSummary.reminder_count} 批待核对` : ''}</button>${entryForm(state.draft, state)}</section>${recent(state)}${state.textSummary?.reminder_count?`<p class="pending-note">${icon('help',16)}${state.textSummary.reminder_count} 批文字／循环记录待处理，尚未自动入账</p>`:''}</div>`; }
function ranking(state) {
  const stats = state.stats;
  return `<section class="card ranking-card"><div class="card-heading"><h2>支出分类排行</h2><span class="muted">${stats.categories.length} 个分类</span></div>${stats.categories.length ? `<div class="ranking-list">${stats.categories.map((c, i) => `<button class="ranking-row" data-action="category-bills" data-id="${e(c.id)}"><span class="rank-number">${i + 1}</span>${categoryIcon(c, 'small')}<span class="rank-content"><span class="rank-top"><strong>${e(c.name)}</strong><b class="money">${money(c.amount_minor)}</b><span class="rank-percent">${(c.amount_minor / stats.totals.expense_minor * 100).toFixed(1)}%</span></span><span class="rank-track"><span style="width:${c.amount_minor / stats.categories[0].amount_minor * 100}%;background:${color(c)}"></span></span></span></button>`).join('')}</div>` : empty('还没有支出', '有了记录，就能看到钱花在哪里。')}</section>`;
}
export function statsPage(state) {
  if (!state.stats) return loading();
  const s = state.stats, prefix = state.period === 'month' ? '本月' : state.period === 'quarter' ? '本季' : '本年';
  const heading = state.chart === 'bar' ? `${prefix}支出趋势` : state.chart === 'line' ? '分类变化' : '支出分布';
  const modeButtons = `<div class="segmented chart-switch" role="group" aria-label="图表类型">${[['bar', '柱状'], ['line', '折线'], ['pie', '饼图']].map(([id, name]) => `<button class="${state.chart === id ? 'active' : ''}" data-action="chart" data-value="${id}" aria-pressed="${state.chart === id}">${icon(id, 15)}<span>${name}</span></button>`).join('')}</div>`;
  return `<div class="stats-period"><div class="segmented period-switch" role="group" aria-label="统计周期">${[['month', '按月'], ['quarter', '按季'], ['year', '按年']].map(([id, name]) => `<button class="${state.period === id ? 'active' : ''}" aria-pressed="${state.period === id}" data-action="period" data-value="${id}">${name}</button>`).join('')}</div><div class="mobile-month">${monthControl(state)}</div><span class="period-caption">${e(s.from)} — ${e(s.to)}</span></div>
    ${summary(s.totals, prefix)}<section class="mobile-stat-hero"><span>${prefix}支出</span><strong class="money">${money(s.totals.expense_minor)}</strong><p>${prefix}收入 ${money(s.totals.income_minor)} <span>|</span> 结余 ${money(s.totals.income_minor - s.totals.expense_minor)}</p>${icon('bar', 75)}</section>
    <div class="workbench"><div class="workbench-main"><div class="analytics-grid"><section class="card chart-card"><div class="card-heading"><h2>${heading}</h2>${modeButtons}</div><p class="chart-caption">${state.chart === 'pie' ? '所选期间，各分类支出占比' : state.chart === 'line' ? '各分类在不同时间的支出变化' : '每天花了多少，分别花在哪里'}<span>${state.chart === 'pie' ? '' : '单位：元'}</span></p>${s.totals.expense_minor ? `<div class="chart-wrap ${state.chart === 'pie' ? 'pie-wrap' : ''}"><canvas id="expense-chart" role="img" aria-label="${e(heading)}，支出合计 ${money(s.totals.expense_minor)}，详细金额见下方数据表"></canvas></div><div class="chart-legend">${s.categories.map(c => `<button data-action="category-bills" data-id="${e(c.id)}"><i style="background:${color(c)}"></i>${e(c.name)}</button>`).join('')}</div><details class="chart-data"><summary>查看图表数据</summary><div class="table-scroll"><table><caption>金额与图形使用同一统计结果</caption><thead><tr><th>时间</th><th>分类</th><th>金额</th></tr></thead><tbody>${s.series.map(v => `<tr><td>${e(v.bucket)}</td><td>${e(s.categories.find(c => c.id === v.category_id)?.name)}</td><td>${money(v.amount_minor)}</td></tr>`).join('')}</tbody></table></div></details>` : empty('这段时间还没有支出', '记下一笔，开始了解你的日常开销。', '<button class="button primary" data-action="new-entry">记一笔</button>')}</section>${ranking(state)}</div><div class="desktop-recent">${recent(state, true)}</div></div><aside class="card quick-entry">${entryForm(state.draft, state, 'quick')}</aside></div>`;
}
export function billsPage(state) {
  const b = state.bills;
  if (!b) return loading();
  const grouped = Object.groupBy(b.entries, x => x.occurred_on);
  return `<div class="mobile-month bills-month">${monthControl(state)}</div>${summary(b.totals, state.billRange || state.filters.type || state.filters.category_id || state.filters.q ? '筛选' : '本月', true)}<section class="card bills-card"><div class="bills-toolbar"><div class="segmented"><button data-action="filter-type" data-value="" class="${!state.filters.type ? 'active' : ''}">全部</button><button data-action="filter-type" data-value="expense" class="${state.filters.type === 'expense' ? 'active' : ''}">支出</button><button data-action="filter-type" data-value="income" class="${state.filters.type === 'income' ? 'active' : ''}">收入</button></div><form class="search-form" data-form="search"><label>${icon('search', 17)}<input name="q" aria-label="搜索备注、分类或金额" placeholder="搜索备注、分类或金额" maxlength="200" value="${e(state.filters.q)}" /></label><button class="icon-button" aria-label="搜索" type="submit">${icon('arrow', 17)}</button></form><button class="button secondary filter-button" data-action="filters" aria-label="筛选账单">${icon('filter', 16)}<span>筛选</span></button><button class="button secondary export-filter" data-action="export-filter">${icon('download', 16)}导出当前筛选</button></div><div class="filter-summary"><span>${state.billRange ? `${e(state.billRange.from)} 至 ${e(state.billRange.to)} · ` : ''}共 ${b.totals.count} 笔记录${state.filters.category_id ? ` · ${e(state.categories.find(c => c.id === state.filters.category_id)?.name)}` : ''}</span>${state.filters.q || state.filters.category_id || state.filters.type ? '<button class="text-button" data-action="clear-filters">清除筛选</button>' : ''}<span class="balance-explanation">结余为本期收入减支出</span></div>${b.entries.length ? `<div class="desktop-bills table-scroll"><table class="entries-table"><thead><tr><th>日期</th><th>备注</th><th>分类</th><th class="numeric">金额</th><th>操作</th></tr></thead><tbody>${tableRows(b.entries)}</tbody></table></div><div class="mobile-bills">${Object.entries(grouped).map(([day, entries]) => { const total = b.days.find(x => x.occurred_on === day); return `<section class="day-group"><div class="day-heading"><button data-action="backdate" data-date="${e(day)}">${dayLabel(day)}</button><span>${total.expense_minor ? `支出 ${money(total.expense_minor)}` : ''}${total.income_minor ? ` 收入 ${money(total.income_minor)}` : ''}</span></div>${entries.map(x => recordRow(x)).join('')}</section>`; }).join('')}</div><div class="pagination"><span>第 ${Math.floor(state.offset / 50) + 1} / ${Math.max(1, Math.ceil(b.totals.count / 50))} 页</span><button class="button secondary" data-action="page-prev" ${state.offset === 0 ? 'disabled' : ''}>上一页</button><button class="button secondary" data-action="page-next" ${state.offset + 50 >= b.totals.count ? 'disabled' : ''}>下一页</button></div>` : empty('没有找到记录', state.filters.q || state.filters.category_id || state.filters.type ? '试试调整筛选条件，或查看其他月份。' : '这个月还没有账目，先记下第一笔。', '<button class="button primary" data-action="new-entry">记一笔</button>')}</section>`;
}
function settingRow(symbol, label, action, description = '') { return `<button class="setting-row" data-action="${action}"><span class="setting-symbol">${icon(symbol, 21)}</span><span class="setting-copy"><strong>${label}</strong>${description ? `<small>${e(description)}</small>` : ''}</span>${icon('right', 17)}</button>`; }
export function settingsPage(state) {
  const ledger = state.session.ledger;
  return `<div class="settings-layout"><section class="card profile-card"><span class="profile-avatar">${icon('user', 40)}</span><div><h2>${e(ledger.name)}</h2><p>人民币 · 上海时区</p><small>${state.session.local ? '本地预览身份' : e(state.session.user.email)}</small></div><button class="icon-button" data-action="ledgers" aria-label="查看与切换账本">${icon('right')}</button></section><section class="card settings-group"><h2>数据与账本</h2>${settingRow('settings', '分类管理', 'categories', '管理名称、颜色与常用分类')}${settingRow('file', '文字与循环记录', 'text-records', `多笔拆分、订阅周期与待核对提醒${state.textSummary?.reminder_count ? ` · ${state.textSummary.reminder_count} 批待处理` : ''}`)}${settingRow('download', '导出账单', 'export-all', '导出全部有效账目为 CSV')}${settingRow('upload', '备份与恢复', 'backup', '完整备份、校验与候选账本恢复')}${settingRow('trash', '回收站', 'trash', '恢复删除的记录')}</section><section class="card settings-group">${settingRow('settings', '显示设置', 'display', '选择常用图表与显示密度')}${settingRow('logout', '退出登录', 'logout')}</section><p class="version-label">MoneyTalk · 让生活更有数<br><span>v0.1.0${state.session.local ? ' · 本地预览，尚未部署云端' : ''}</span></p></div>`;
}
export function loading() { return '<div class="loading-grid" aria-label="正在加载账本" aria-busy="true"><div></div><div></div><div></div></div>'; }
export function categoryManager(state) {
  return `<p class="dialog-intro">分类颜色在账单和图表中保持一致。停用后保留历史记录。</p><button class="button primary" data-action="new-category">${icon('plus', 17)}添加分类</button><div class="category-manager">${['expense', 'income'].map(type => `<h3>${type === 'expense' ? '支出分类' : '收入分类'}</h3>${state.categories.filter(c => c.type === type).map(c => `<button class="manage-category" data-action="edit-category" data-id="${e(c.id)}">${categoryIcon(c)}<strong>${e(c.name)}</strong>${c.archived ? '<span class="status-tag">已停用</span>' : ''}<span class="color-swatch" style="background:${color(c)}"></span>${icon('right', 16)}</button>`).join('')}`).join('')}</div>`;
}
export function categoryEditor(category = {}) {
  const c = { name: '', type: 'expense', color_key: 'blue', icon: 'wallet', sort_order: 100, archived: false, ...category };
  return `<form data-form="category" class="standard-form"><label>名称<input name="name" maxlength="32" required value="${e(c.name)}" /></label><label>类型<select name="type" ${category.id ? 'disabled' : ''}><option value="expense" ${c.type === 'expense' ? 'selected' : ''}>支出</option><option value="income" ${c.type === 'income' ? 'selected' : ''}>收入</option></select></label><fieldset><legend>分类颜色</legend><div class="color-options">${Object.entries(PALETTE).map(([key, value]) => `<label title="${colorNames[key]}"><input type="radio" name="color_key" value="${key}" ${c.color_key === key ? 'checked' : ''} /><span style="background:${value}">${icon('check', 18)}</span><span class="sr-only">${colorNames[key]}</span></label>`).join('')}</div></fieldset><label>图标<select name="icon">${[...new Map(DEFAULT_CATEGORIES.map(x => [x.icon, x.name])).entries()].map(([id, name]) => `<option value="${id}" ${c.icon === id ? 'selected' : ''}>${name}</option>`).join('')}</select></label><label>排序（数字越小越靠前）<input name="sort_order" type="number" min="0" max="10000" value="${c.sort_order}" /></label>${category.id ? `<label class="checkbox-label"><input type="checkbox" name="archived" ${c.archived ? 'checked' : ''} />停用此分类，保留历史记录</label>` : ''}<p class="field-error" role="alert" id="category-error"></p><button class="button primary" type="submit">保存分类</button></form>`;
}
